name: Workflow Call Test

on:
   workflow_dispatch:
        inputs:
            random:
                required: true
                type: string
                default: dev
jobs:
    called:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ inputs.random }}"
