name: Workflow Call Test

on:
    workflow_call:
        inputs:
            random:
                required: true
                type: string
jobs:
    called:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ inputs.random }}"
